### ISSUE TITLE
emu64.sh

### ISSUE THREAD

**Issue by Butteboy** [idun-project/idun-vice#2]
Not really an issue, but update readme.MD to reflect you need to run emu64.sh not emu.sh.

But got it up and running on hardware and working.

**Comment by Butteboy** [comment]
Sorry, mistake on my part.

**Comment by idun-project** [comment]
Hi. Glad you worked it out. And there should be a note in the README:

emu64.sh is sort of ancillary.  It exists mainly because the `go64` shell command doesn't work in the emulator. Instead, you can exit the x128 emulator (`emu.sh`), and start the x64sc emulator (`emu64.sh`), without upsetting the state of the cartridge.
